<a href="https://colab.research.google.com/github/hiitsmocha/learn-pytorch/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

TENSOR MATH OPERATIONS
- OPERATIONS
- SHORTHAND AND LONGHAND
- REASSIGNMENT

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Remainder Modulus

In [14]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [16]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
# Reassignment
# tensor_a = tensor_a + tensor_b
# --> tensor_a.add(tensor_b) updates tensor_a
tensor_a.add(tensor_b)

tensor([11, 14, 17, 20])

In [21]:
tensor_a.add_(tensor_b)

tensor([16, 20, 24, 28])

In [22]:
tensor_a.add_(tensor_b)

tensor([21, 26, 31, 36])